---
title: "DataFest"
author: "Carol Zhou"
date: "2024-03-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Download full datasets (NOT SAMPLE) and import
```{r cars}
responses <- read.csv("full/responses.csv")
items <- read.csv("full/items.csv")
checkpoints_eoc <- read.csv("full/checkpoints_eoc.csv")
checkpoints_pulse <- read.csv("full/checkpoints_pulse.csv")
media_views <- read.csv("full/media_views.csv") #Starts from CHAPTER 4
page_views <- read.csv("full/page_views.csv")
```

```{r pressure, echo=FALSE}
#Filter EOC scores for only book 1
books <- "College / Statistics and Data Science (ABC)"
checkpoints_eoc_book1 <- checkpoints_eoc  %>%
  filter(book == books) %>%
  select(student_id, chapter_number, EOC)

#Divide EOC scores by chapter, arranged by student id
unique_chapters_book1 <- unique(checkpoints_eoc_book1$chapter_number)
subset_list_book1 <- list()

# Loop through each unique student ID
for (numbers in unique_chapters_book1) {
  # Create subset for the current ID
  subset_data_book1 <- subset(checkpoints_eoc_book1, chapter_number == numbers)
  
  # Store the subset in the list
  subset_list_book1[[as.character(numbers)]] <- subset_data_book1
}
```

Chapter 2
```{r}
book1_chapter1 <- subset_list_book1[[unique_chapters_book1[2]]]
book1_chapter1$book <- books
unique_students_b1c1 <- unique(book1_chapter1$student_id)
x2 <- data.frame(matrix(nrow = length(unique_students_b1c1), ncol = 0))
rownames(x2) <- unique_students_b1c1

responses$scores <- responses$points_earned/responses$points_possible
responses_b1c1 <- responses %>% 
  filter(book == books, chapter_number == 2)
item_scores <- responses_b1c1 %>% 
  group_by(student_id, item_type) %>% 
  summarise(mean_scores = mean(scores, na.rm = TRUE)) %>%
  ungroup()
item_scores <- item_scores %>%
  mutate(item_type = ifelse(item_type == "learnosity_activity", "learnosity", item_type)) %>%
  group_by(student_id, item_type) %>%
  summarise(mean_scores = sum(mean_scores)) %>%
  ungroup()

item_scores <- pivot_wider(item_scores, names_from = item_type, values_from = mean_scores)
x2$codes_score <- item_scores$code[match(unique_students_b1c1, item_scores$student_id)]
x2$learnocity_score <- item_scores$learnosity[match(unique_students_b1c1, item_scores$student_id)]

page_views_b1c1 <- page_views %>% 
  filter(book == books, chapter_number == 2)

was_complete_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_was_complete = mean(was_complete))
x2$was_complete <- was_complete_avg$mean_was_complete[match(unique_students_b1c1, was_complete_avg$student_id)]

engaged_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_engaged = mean(engaged))
x2$engaged <- engaged_avg$mean_engaged[match(unique_students_b1c1, engaged_avg$student_id)]

idle_brief_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_idle_brief = mean(idle_brief))
x2$idle_brief <- idle_brief_avg$mean_idle_brief[match(unique_students_b1c1, idle_brief_avg$student_id)]

idle_long_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_idle_long = mean(idle_long))
x2$idle_long <- idle_long_avg$mean_idle_long[match(unique_students_b1c1, idle_long_avg$student_id)]

off_page_brief_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_off_page_brief = mean(off_page_brief))
x2$off_page_brief <- off_page_brief_avg$mean_off_page_brief[match(unique_students_b1c1, off_page_brief_avg$student_id)]

off_page_long_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_off_page_long = mean(off_page_long))
x2$off_page_long <- off_page_long_avg$mean_off_page_long[match(unique_students_b1c1, off_page_long_avg$student_id)]

checkpoints_pulse_b1c1 <- checkpoints_pulse %>% 
  filter(book == books, chapter_number == 2) %>%
  select(student_id, construct, response)
  
checkpoints_pulse_b1c1 <- checkpoints_pulse_b1c1 %>%
  group_by(student_id,construct) %>%
  summarise(mean_response = mean(response, na.rm = T))
  
checkpoints_pulse_b1c1 <- pivot_wider(checkpoints_pulse_b1c1, names_from = construct, values_from = mean_response)

x2$Cost <- checkpoints_pulse_b1c1$Cost[match(unique_students_b1c1, checkpoints_pulse_b1c1$student_id)]
x2$Expectancy <- checkpoints_pulse_b1c1$Expectancy[match(unique_students_b1c1, checkpoints_pulse_b1c1$student_id)]
x2$intrinsic_value <- checkpoints_pulse_b1c1$`Intrinsic Value`[match(unique_students_b1c1, checkpoints_pulse_b1c1$student_id)]
x2$utility_value <- checkpoints_pulse_b1c1$`Utility Value`[match(unique_students_b1c1, checkpoints_pulse_b1c1$student_id)]

book1_chapter1 <- book1_chapter1 %>%
  group_by(student_id) %>%
  summarize(mean_EOC = mean(EOC, na.rm=T))
y2 <- book1_chapter1$mean_EOC

x2_clean = na.omit(x2)

book1_chapter1 <- book1_chapter1[book1_chapter1$student_id %in% rownames(x2_clean), ]

y2_clean <- book1_chapter1[book1_chapter1$student_id %in% rownames(x2_clean), ]
```

Chapter 3
```{r}
book1_chapter1 <- subset_list_book1[[unique_chapters_book1[3]]]
book1_chapter1$book <- books
unique_students_b1c1 <- unique(book1_chapter1$student_id)
x3 <- data.frame(matrix(nrow = length(unique_students_b1c1), ncol = 0))
rownames(x3) <- unique_students_b1c1

responses$scores <- responses$points_earned/responses$points_possible
responses_b1c1 <- responses %>% 
  filter(book == books, chapter_number == 3)
item_scores <- responses_b1c1 %>% 
  group_by(student_id, item_type) %>% 
  summarise(mean_scores = mean(scores, na.rm = TRUE)) %>%
  ungroup()
item_scores <- item_scores %>%
  mutate(item_type = ifelse(item_type == "learnosity_activity", "learnosity", item_type)) %>%
  group_by(student_id, item_type) %>%
  summarise(mean_scores = sum(mean_scores)) %>%
  ungroup()

item_scores <- pivot_wider(item_scores, names_from = item_type, values_from = mean_scores)
x3$codes_score <- item_scores$code[match(unique_students_b1c1, item_scores$student_id)]
x3$learnocity_score <- item_scores$learnosity[match(unique_students_b1c1, item_scores$student_id)]

page_views_b1c1 <- page_views %>% 
  filter(book == books, chapter_number == 3)

was_complete_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_was_complete = mean(was_complete))
x3$was_complete <- was_complete_avg$mean_was_complete[match(unique_students_b1c1, was_complete_avg$student_id)]

engaged_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_engaged = mean(engaged))
x3$engaged <- engaged_avg$mean_engaged[match(unique_students_b1c1, engaged_avg$student_id)]

idle_brief_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_idle_brief = mean(idle_brief))
x3$idle_brief <- idle_brief_avg$mean_idle_brief[match(unique_students_b1c1, idle_brief_avg$student_id)]

idle_long_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_idle_long = mean(idle_long))
x3$idle_long <- idle_long_avg$mean_idle_long[match(unique_students_b1c1, idle_long_avg$student_id)]

off_page_brief_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_off_page_brief = mean(off_page_brief))
x3$off_page_brief <- off_page_brief_avg$mean_off_page_brief[match(unique_students_b1c1, off_page_brief_avg$student_id)]

off_page_long_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_off_page_long = mean(off_page_long))
x3$off_page_long <- off_page_long_avg$mean_off_page_long[match(unique_students_b1c1, off_page_long_avg$student_id)]

checkpoints_pulse_b1c1 <- checkpoints_pulse %>% 
  filter(book == books, chapter_number == 3) %>%
  select(student_id, construct, response)
  
checkpoints_pulse_b1c1 <- checkpoints_pulse_b1c1 %>%
  group_by(student_id,construct) %>%
  summarise(mean_response = mean(response, na.rm = T))
  
checkpoints_pulse_b1c1 <- pivot_wider(checkpoints_pulse_b1c1, names_from = construct, values_from = mean_response)

x3$Cost <- checkpoints_pulse_b1c1$Cost[match(unique_students_b1c1, checkpoints_pulse_b1c1$student_id)]
x3$Expectancy <- checkpoints_pulse_b1c1$Expectancy[match(unique_students_b1c1, checkpoints_pulse_b1c1$student_id)]
x3$intrinsic_value <- checkpoints_pulse_b1c1$`Intrinsic Value`[match(unique_students_b1c1, checkpoints_pulse_b1c1$student_id)]
x3$utility_value <- checkpoints_pulse_b1c1$`Utility Value`[match(unique_students_b1c1, checkpoints_pulse_b1c1$student_id)]

book1_chapter1 <- book1_chapter1 %>%
  group_by(student_id) %>%
  summarize(mean_EOC = mean(EOC, na.rm = T))
y3 <- book1_chapter1$mean_EOC

x3_clean = na.omit(x3)

book1_chapter1 <- book1_chapter1[book1_chapter1$student_id %in% rownames(x3_clean), ]

y3_clean <- book1_chapter1[book1_chapter1$student_id %in% rownames(x3_clean), ]
```

Chapter 4
```{r}
book1_chapter1 <- subset_list_book1[[unique_chapters_book1[4]]]
book1_chapter1$book <- books
unique_students_b1c1 <- unique(book1_chapter1$student_id)
x4 <- data.frame(matrix(nrow = length(unique_students_b1c1), ncol = 0))
rownames(x4) <- unique_students_b1c1

responses$scores <- responses$points_earned/responses$points_possible
responses_b1c1 <- responses %>% 
  filter(book == books, chapter_number == 4)
item_scores <- responses_b1c1 %>% 
  group_by(student_id, item_type) %>% 
  summarise(mean_scores = mean(scores, na.rm = TRUE)) %>%
  ungroup()
item_scores <- item_scores %>%
  mutate(item_type = ifelse(item_type == "learnosity_activity", "learnosity", item_type)) %>%
  group_by(student_id, item_type) %>%
  summarise(mean_scores = sum(mean_scores)) %>%
  ungroup()

item_scores <- pivot_wider(item_scores, names_from = item_type, values_from = mean_scores)
x4$codes_score <- item_scores$code[match(unique_students_b1c1, item_scores$student_id)]
x4$learnocity_score <- item_scores$learnosity[match(unique_students_b1c1, item_scores$student_id)]

page_views_b1c1 <- page_views %>% 
  filter(book == books, chapter_number == 4)

was_complete_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_was_complete = mean(was_complete))
x4$was_complete <- was_complete_avg$mean_was_complete[match(unique_students_b1c1, was_complete_avg$student_id)]

engaged_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_engaged = mean(engaged))
x4$engaged <- engaged_avg$mean_engaged[match(unique_students_b1c1, engaged_avg$student_id)]

idle_brief_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_idle_brief = mean(idle_brief))
x4$idle_brief <- idle_brief_avg$mean_idle_brief[match(unique_students_b1c1, idle_brief_avg$student_id)]

idle_long_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_idle_long = mean(idle_long))
x4$idle_long <- idle_long_avg$mean_idle_long[match(unique_students_b1c1, idle_long_avg$student_id)]

off_page_brief_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_off_page_brief = mean(off_page_brief))
x4$off_page_brief <- off_page_brief_avg$mean_off_page_brief[match(unique_students_b1c1, off_page_brief_avg$student_id)]

off_page_long_avg <- page_views_b1c1 %>%
  group_by(student_id) %>%
  summarise(mean_off_page_long = mean(off_page_long))
x4$off_page_long <- off_page_long_avg$mean_off_page_long[match(unique_students_b1c1, off_page_long_avg$student_id)]

media_views$dt_started_new = sub("T", " ", media_views$dt_started)
media_views$dt_started_new = sub("Z", " ", media_views$dt_started_new)
media_views$dt_last_event_new = sub("T", " ", media_views$dt_last_event)
media_views$dt_last_event_new = sub("Z", " ", media_views$dt_last_event_new)
media_views$time_spent = difftime(media_views$dt_last_event_new, media_views$dt_started_new, units = "mins")
media_views$time_spent_new = as.numeric(sub(" mins", "", media_views$time_spent))

prop_video_avg = media_views %>%
  filter(chapter_number == 4) %>%
  group_by(student_id) %>%
  summarise(mean_prop_video = mean(proportion_video, na.rm = T))
x4$prop_video = prop_video_avg$mean_prop_video[match(unique_students_b1c1, prop_video_avg$student_id)]

time_spent_avg = media_views %>%
  filter(chapter_number == 4) %>%
  group_by(student_id) %>%
  summarise(mean_time_spent = mean(time_spent_new, na.rm = T))
x4$video_time_spent = time_spent_avg$mean_time_spent[match(unique_students_b1c1, time_spent_avg$student_id)]

checkpoints_pulse_b1c1 <- checkpoints_pulse %>% 
  filter(book == books, chapter_number == 4) %>%
  select(student_id, construct, response)
  
checkpoints_pulse_b1c1 <- checkpoints_pulse_b1c1 %>%
  group_by(student_id,construct) %>%
  summarise(mean_response = mean(response, na.rm = T))
  
checkpoints_pulse_b1c1 <- pivot_wider(checkpoints_pulse_b1c1, names_from = construct, values_from = mean_response)

x4$Cost <- checkpoints_pulse_b1c1$Cost[match(unique_students_b1c1, checkpoints_pulse_b1c1$student_id)]
x4$Expectancy <- checkpoints_pulse_b1c1$Expectancy[match(unique_students_b1c1, checkpoints_pulse_b1c1$student_id)]
x4$intrinsic_value <- checkpoints_pulse_b1c1$`Intrinsic Value`[match(unique_students_b1c1, checkpoints_pulse_b1c1$student_id)]
x4$utility_value <- checkpoints_pulse_b1c1$`Utility Value`[match(unique_students_b1c1, checkpoints_pulse_b1c1$student_id)]

book1_chapter1 <- book1_chapter1 %>%
  group_by(student_id) %>%
  summarize(mean_EOC = mean(EOC, na.rm=T))
y4 <- book1_chapter1$mean_EOC

x4_clean = na.omit(x4)

book1_chapter1 <- book1_chapter1[book1_chapter1$student_id %in% rownames(x4_clean), ]

y4_clean <- book1_chapter1[book1_chapter1$student_id %in% rownames(x4_clean), ]
```

```{r}
minMax <- function(x) {
  (x - min(x)) / (max(x) - min(x))
}
x2_clean_scaled <- as.data.frame(lapply(x2_clean, minMax))
x3_clean_scaled <- as.data.frame(lapply(x3_clean, minMax))
x4_clean_scaled <- as.data.frame(lapply(x4_clean, minMax))
x14_clean_scaled <- as.data.frame(lapply(x14_clean, minMax))
```

```{r}
library(caret)
index2 <- createDataPartition(y2_clean$mean_EOC, p = 0.8, list = FALSE)
x2_train <- x2_clean_scaled[index2, ]
x2_test <- x2_clean_scaled[-index2, ]
y2_train <- y2_clean[index2, "mean_EOC"]
y2_test <- y2_clean[-index2, "mean_EOC"]

index3 <- createDataPartition(y3_clean$mean_EOC, p = 0.8, list = FALSE)
x3_train <- x3_clean_scaled[index3, ]
x3_test <- x3_clean_scaled[-index3, ]
y3_train <- y3_clean[index3, "mean_EOC"]
y3_test <- y3_clean[-index3, "mean_EOC"]

index4 <- createDataPartition(y4_clean$mean_EOC, p = 0.8, list = FALSE)
x4_train <- x4_clean_scaled[index4, ]
x4_test <- x4_clean_scaled[-index4, ]
y4_train <- y4_clean[index4, "mean_EOC"]
y4_test <- y4_clean[-index4, "mean_EOC"]
```


```{r}
library(glmnet)
cv_model2 <- cv.glmnet(as.matrix(x2_train), as.matrix(y2_train), alpha = 1)
best_lambda2 <- cv_model2$lambda.min
best_model2 <- glmnet(as.matrix(x2_train), as.matrix(y2_train), alpha = 1, lambda = best_lambda2)
coef(best_model2)
```


```{r}
coefficients2 <- coef(best_model2)
y_predicted2 <- predict(best_model2, s = best_lambda2, newx = as.matrix(x2_test))
mean((as.matrix(y2_test)-y_predicted2)^2)
```

```{r}
cv_model3 <- cv.glmnet(as.matrix(x3_train), as.matrix(y3_train), alpha = 1)
best_lambda3 <- cv_model3$lambda.min
best_model3 <- glmnet(as.matrix(x3_train), as.matrix(y3_train), alpha = 1, lambda = best_lambda3)
coef(best_model3)
```

```{r}
coefficients3 <- coef(best_model3)
y_predicted3 <- predict(best_model3, s = best_lambda3, newx = as.matrix(x3_test))
mean((as.matrix(y3_test)-y_predicted3)^2)
```


```{r}
cv_model4 <- cv.glmnet(as.matrix(x4_train), as.matrix(y4_train), alpha = 1)
best_lambda4 <- cv_model4$lambda.min
best_model4 <- glmnet(as.matrix(x4_train), as.matrix(y4_train), alpha = 1, lambda = best_lambda4)
coef(best_model4)
```

```{r}
coefficients4 <- coef(best_model4)
y_predicted4 <- predict(best_model4, s = best_lambda4, newx = as.matrix(x4_test))
mean((as.matrix(y4_test)-y_predicted4)^2)
```


```{r}
df = read.csv("DataFest - Sheet1.csv")
normalize_and_multiply <- function(x) {
  max_abs <- max(abs(x), na.rm = TRUE)
  result <- ifelse(is.na(x), NA, x / max_abs)
  return(result)
}
```


```{r}
df_page = df[3:8,]
row_names <- df_page[,1]
df_page <- df_page[, -1]
rownames(df_page) <- row_names
colnames(df_page) <- 1:13
df_page<-as.data.frame(t(df_page))
df_page <- tibble::rownames_to_column(df_page, var = "Chapter")
df_page$Chapter <- as.numeric(df_page$Chapter)

df_page1 <- df_page %>% select(Chapter, was_complete, engaged)
df_page1 <- pivot_longer(df_page1, cols=colnames(df_page1[,2:3]), names_to = "Coefficient", values_to = "Value")
df_page1$Value <- ifelse(is.na(df_page1$Value), 0, df_page1$Value)
df_page1$Value <-df_page1$Value/max(abs(df_page1$Value)) 
ggplot(df_page1, aes(x = Chapter, y = Value, col = Coefficient)) +
  geom_step() +
  scale_x_continuous(breaks = unique(df_page1$Chapter)) +
  ylim(-1, 1)

df_page2 <- df_page %>% select(Chapter, idle_brief, idle_long, off_page_brief, off_page_long)
df_page2 <- pivot_longer(df_page2, cols=colnames(df_page2[,2:5]), names_to = "Coefficient", values_to = "Value")
df_page2$Value <- ifelse(is.na(df_page2$Value), 0, df_page2$Value)
df_page2$Value <-df_page2$Value/max(abs(df_page2$Value)) 
ggplot(df_page2, aes(x = Chapter, y = Value, col = Coefficient)) +
  geom_step() +
  scale_x_continuous(breaks = unique(df_page2$Chapter)) +
  ylim(-1, 1)
```
```{r}
df_media = df[13:14,]
row_names <- df_media[,1]
df_media <- df_media[, -1]
rownames(df_media) <- row_names
colnames(df_media) <- 1:13
df_media<-as.data.frame(t(df_media))
df_media <- tibble::rownames_to_column(df_media, var = "Chapter")
df_media$Chapter <- as.numeric(df_media$Chapter)
df_media <- pivot_longer(df_media, cols=colnames(df_media[,2:3]), names_to = "Coefficient", values_to = "Value")
df_media$Value <- ifelse(is.na(df_media$Value), 0, df_media$Value)
df_media$Value <-df_media$Value/max(abs(df_media$Value)) 
ggplot(df_media, aes(x = Chapter, y = Value, col = Coefficient)) +
  geom_step() +
  scale_x_continuous(breaks = unique(df_media$Chapter)) +
  ylim(-1, 1)
```

```{r}
df_responses = df[1:2,]
row_names <- df_responses[,1]
df_responses <- df_responses[, -1]
rownames(df_responses) <- row_names
colnames(df_responses) <- 1:13
df_responses<-as.data.frame(t(df_responses))
df_responses <- tibble::rownames_to_column(df_responses, var = "Chapter")
df_responses$Chapter <- as.numeric(df_responses$Chapter)
df_responses <- pivot_longer(df_responses, cols=colnames(df_responses[,2:3]), names_to = "Coefficient", values_to = "Value")
df_responses$Value <- ifelse(is.na(df_responses$Value), 0, df_responses$Value)
df_responses$Value <-df_responses$Value/max(abs(df_responses$Value)) 
ggplot(df_responses, aes(x = Chapter, y = Value, col = Coefficient)) +
  geom_step() +
  scale_x_continuous(breaks = unique(df_responses$Chapter)) +
  ylim(-1, 1)
```


```{r}
df_pulse = df[9:12,]
row_names <- df_pulse[,1]
df_pulse <- df_pulse[, -1]
rownames(df_pulse) <- row_names
colnames(df_pulse) <- 1:13
df_pulse<-as.data.frame(t(df_pulse))
df_pulse <- tibble::rownames_to_column(df_pulse, var = "Chapter")
df_pulse$Chapter <- as.numeric(df_pulse$Chapter)
df_pulse <- pivot_longer(df_pulse, cols=colnames(df_pulse[,2:5]), names_to = "Coefficient", values_to = "Value")
df_pulse$Value <- ifelse(is.na(df_pulse$Value), 0, df_pulse$Value)
df_pulse$Value <-df_pulse$Value/max(abs(df_pulse$Value)) 
ggplot(df_pulse, aes(x = Chapter, y = Value, col = Coefficient)) +
  geom_step() +
  scale_x_continuous(breaks = unique(df_pulse$Chapter)) +
  ylim(-1, 1)
```


Ignore below
```{r}
library(mice)
x2_mice = complete(mice(x2, method = 'pmm'))
sum(is.na(x2_mice))
x3_mice = complete(mice(x3, method = 'pmm'))
x4_mice = complete(mice(x4, method = 'pmm'))
x14_mice = complete(mice(x14, method = 'pmm'))
```

```{r}
summary(x4$video_time_spent)
x4_epr = x4 %>%
  filter(video_time_spent > 1.66 - 1.5 * IQR(x4$video_time_spent, na.rm = T) & video_time_spent < 3.22 + 1.5 * IQR(x4$video_time_spent, na.rm = T))
ggplot(x4_epr, aes(prop_video, video_time_spent)) +
  geom_jitter()
```

```{r}
x4$engaged_min = x4$engaged / 1000 / 60
ggplot(x4_epr, aes(video_time_spent, engaged_min)) +
  geom_jitter() +
  geom_smooth()
```

```{r}
#Replace NA with mean of remaining
X1_imputed <- apply(X1, 2, function(x) ifelse(is.na(x), mean(x, na.rm = TRUE), x))

# Split the data into 80% training and 20% testing
train_index <- createDataPartition(y, p = 0.8, list = FALSE)
X1_train <- X1_imputed[train_index, ]
X1_test <- X1_imputed[-train_index, ]
y1_train <- y1[train_index]
y1_test <- y1[-train_index]

cv_model <- cv.glmnet(X1_train, y1_train, alpha = 1)
best_lambda <- cv_model$lambda.min
best_lambda

plot(cv_model) 

#LASSO here, or in python?

best_model <- glmnet(X1_train, y1_train, alpha = 1, lambda = best_lambda)
coefficients1 <- coef(best_model)

y_predicted <- predict(best_model, s = best_lambda, newx = X1_train)

mean((y1_test-y_predicted)^2)
#MSE = 0.06236135
```

